#!/bin/sh -x

echo "Building the appd-poc project...."
./make

cd appd-service

echo "Removing old container for appd-poc"
docker stop appd-poc
docker rm appd-poc

echo "Building docker image with tag appd-poc"
docker build --tag appd-poc:master -f Dockerfile .

echo "Attempting to start appd-poc container.  Note: default port: 8080, option to mount -v (local json dir):/json"
docker run -it -d -p 8080:8080 --name appd-poc appd-poc:master

docker ps
